### ISSUE TITLE
No release?

### ISSUE THREAD

**Issue by Marrionetta** [M1CR0H4CK3R/FKSE#10]
Any reason why there's no release after 7 years? x.x

**Comment by M1CR0H4CK3R** [comment]
@Marrionetta I didn't realize that we never put up a release! I'm going to build the code for a release tomorrow morning. I need to set up the development environment first, and that will take a few hours. The current iteration of the save editor works 100%, I just never realized that we never put up a build... I had a build made in 2018 that I tested and played around with, but for some unexplainable reason, I have since deleted it, and never published it. I apologize.

**Comment by Marrionetta** [comment]
Yaaay~ thank you~!
